### DISCUSSION TITLE
How to horizontally center <asl-google-signin-button>?

### DISCUSSION THREAD

**Discussion by BruceWilcox** [abacritt/angularx-social-login#728] [Q&A] [answered]
I've tried styling the surrounding div with no success.

```
<div *ngIf="! appData.isLoggedin">

        <asl-google-signin-button type="standard"
                                  shape="rectangle"
                                  width="400px"
                                  theme="filled_black"
                                  logo_alignment="left"
                                  text="Sign In"
                                  size="large"></asl-google-signin-button>

</div>
```

**Comment by IanaPushcash** [comment]
Do you mean logo_alignment="center"?

**Comment by chrstphrrbn** [comment]
I assume centering the button in its surrounding container. I'm looking for the same thing! :/

**Comment by lwestfall** [comment, marked as answer]
I'm a little late to the game here, but here's how I fixed this. Put this in your styles .css or in any component that has `asl-google-signin-button` in its template

```css
asl-google-signin-button {
  display: flex !important;
  justify-content: center !important;
  align-items: center !important;
}
```
